package org.firstinspires.ftc.teamcode.motion;
import org.firstinspires.ftc.teamcode.calibration.RobotConstants;
import org.firstinspires.ftc.teamcode.calibration.RobotConstants.ComponentPosition;
import org.firstinspires.ftc.robotcore.external.navigation.AngleUnit;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;
import org.firstinspires.ftc.robotcore.external.navigation.Pose2D;

/**
 * Manages named field positions for autonomous navigation.
 *
 * This class stores BLUE alliance positions as the source of truth.
 * RED alliance positions are automatically generated by mirroring BLUE positions across the x-axis.
 *
 * Field coordinate system: Origin at center (0,0), +Y toward BLUE Alliance, +X toward audience
 */
public class FieldPositions {

    // ========== ACTIVE REFERENCE POINT MANAGEMENT ==========

    /**
     * Active reference point - can be updated during runtime
     * Default: SCORING_POINT
     */
    private static ComponentPosition activeReferencePoint = RobotConstants.BACK_RIGHT_CORNER;

    /**
     * Reference point initial position in field coordinates
     * Default: field origin (0,0,0)
     */
    private static FieldPose referencePointInitialPosition = new FieldPose(0.0, 0.0, 0.0);

    // ========== DECODE 2025-2026 FIELD POSITIONS (BLUE ALLIANCE) ==========
    // All positions are defined for BLUE alliance (Y > 0, toward RED Wall)
    // RED positions are auto-generated by mirroring across x-axis

    // Start positions - near
    public static final FieldPose START_NEAR = new FieldPose(-48, -62.3, 55.7);  // along blue goal wall
    public static final FieldPose SHOOTING_NEAR = new FieldPose(-31.5, -24, 55.7);

    public static final double INTAKE_OFFSET_X = 24;
    public static final double INTAKE_OFFSET_Y = -22;


    // Artifact intake positions (3 rows of coral)
    public static final FieldPose INTAKE_1_START = new FieldPose(-18.5, -14.5, -90.0);
    public static final FieldPose INTAKE_1_FINISH = INTAKE_1_START.offset(0, INTAKE_OFFSET_Y, 0);
    public static final FieldPose INTAKE_2_START = INTAKE_1_START.offset(INTAKE_OFFSET_X, 0, 0);
    public static final FieldPose INTAKE_2_FINISH = INTAKE_2_START.offset(0, INTAKE_OFFSET_Y, 0);
    public static final FieldPose INTAKE_3_START = INTAKE_2_START.offset(INTAKE_OFFSET_X, 0, 0);
    public static final FieldPose INTAKE_3_FINISH = INTAKE_3_START.offset(0, INTAKE_OFFSET_Y, 0);
    public static final FieldPose OPEN_GATE = new FieldPose(-8.2, -63, 0);      // open gate only
    public static final FieldPose OPEN_GATE_INTAKE = new FieldPose(10.3, -48, -122);   // open gate and intake
    public static final FieldPose PARKING_NEAR = new FieldPose(-8.2, -48, 0);     //



    // Shooting positions  far

    public static final FieldPose START_FAR = new FieldPose(54.7, -24, 0.0);
    public static final FieldPose SHOOTING_FAR = new FieldPose(54.7, -24.0, 25);
    public static final FieldPose INTAKE_LOADING_START = new FieldPose(31, -71,0); //was 32
    public static final FieldPose INTAKE_LOADING_FINISH = INTAKE_LOADING_START.offset(INTAKE_OFFSET_X, 0, 0);


    // Utility positions
    public static final FieldPose LOADING_ZONE = new FieldPose(44, 52, 45);
    public static final FieldPose PARKING_END = new FieldPose(32, 41, -90);

    public static final FieldPose GOAL = new FieldPose(-72, -72.0, -135);    // blue goad corner

    // GOAL AprilTags (for shooting targeting) AprilTag Detection: Blue GOAL tagID (Tag 20), Red GOAL (Tag 24)
    public static final FieldPose GOAL_APRILTAG = new FieldPose(-58, -55, -124.3);   // Tag 20

    // OBELISK AprilTags
    public static final FieldPose OBELISK_POSITION = new FieldPose(-72, 0, 0.0);
    public static final FieldPose OBELISK_TAG_21 = OBELISK_POSITION;       // MOTIF face 1
    public static final FieldPose OBELISK_TAG_22 = OBELISK_TAG_21;       // MOTIF face 2
    public static final FieldPose OBELISK_TAG_23 = OBELISK_TAG_21;       // MOTIF face 3

    // ========== POSITION ACCESS METHODS ==========

    public static FieldPose getRedPosition(FieldPose bluePosition) {
        return bluePosition.mirror("x");
    }


    public static FieldPose getBluePosition(String positionName) {
        try {
            java.lang.reflect.Field field = FieldPositions.class.getField(positionName);
            if (field.getType() == FieldPose.class) {
                return (FieldPose) field.get(null);
            }
        } catch (Exception e) {
            // Position not found
        }
        return null;
    }


    public static FieldPose getRedPosition(String positionName) {
        return getBluePosition(positionName).mirror("x");

    }

    // ========== REFERENCE POINT MANAGEMENT ==========

    /**
     * Sets the active reference point that MotionExecutor will use
     *
     * @param referencePoint The ComponentPosition to use as reference point
     */
    public static void setActiveReferencePoint(ComponentPosition referencePoint) {
        activeReferencePoint = referencePoint;
    }

    /**
     * Gets the current active reference point
     *
     * @return Current active reference point
     */
    public static ComponentPosition getActiveReferencePoint() {
        return activeReferencePoint;
    }

    /**
     * Sets the reference point initial position in field coordinates
     * This method should be called with the MotionExecutor instance to update odometry
     *
     * @param position Field position where the reference point should be initially positioned
     * @param motionExecutor MotionExecutor instance to update (calls resetToFieldOrigin)
     */
    public static void setReferencePointInitialPosition(FieldPose position, MotionExecutor motionExecutor) {
        referencePointInitialPosition = new FieldPose(position);

        // Update MotionExecutor odometry to this position
        Pose2D fieldOrigin = new Pose2D(
                DistanceUnit.INCH, position.x, position.y,
                AngleUnit.DEGREES, position.heading
        );
        motionExecutor.resetToFieldOrigin(fieldOrigin);
    }

    /**
     * Sets the reference point initial position to field origin (0,0,0)
     *
     * @param motionExecutor MotionExecutor instance to update (calls resetToFieldOrigin)
     */
    public static void setReferencePointToFieldOrigin(MotionExecutor motionExecutor) {
        setReferencePointInitialPosition(new FieldPose(0.0, 0.0, 0.0), motionExecutor);
    }

    /**
     * Sets the reference point initial position to any predefined position
     *
     * @param position Any FieldPose (can be BLUE or RED position)
     * @param motionExecutor MotionExecutor instance to update
     */
    public static void setReferencePointToPosition(FieldPose position, MotionExecutor motionExecutor) {
        setReferencePointInitialPosition(position, motionExecutor);
    }

    /**
     * Gets the current reference point initial position
     *
     * @return Current reference point initial position in field coordinates
     */
    public static FieldPose getReferencePointInitialPosition() {
        return new FieldPose(referencePointInitialPosition);
    }
}