package org.firstinspires.ftc.teamcode.motion;
import org.firstinspires.ftc.teamcode.calibration.RobotConstants;
import org.firstinspires.ftc.teamcode.calibration.RobotConstants.ComponentPosition;
import org.firstinspires.ftc.robotcore.external.navigation.AngleUnit;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;
import org.firstinspires.ftc.robotcore.external.navigation.Pose2D;

/**
 * Manages named field positions for autonomous navigation.
 * 
 * This class stores BLUE alliance positions as the source of truth.
 * RED alliance positions are automatically generated by mirroring BLUE positions across the x-axis.
 * 
 * Field coordinate system: Origin at center (0,0), +Y toward BLUE Alliance, +X toward audience
 */
public class FieldPositions {
    
    // ========== ACTIVE REFERENCE POINT MANAGEMENT ==========
    
    /**
     * Active reference point - can be updated during runtime
     * Default: SCORING_POINT
     */
    private static ComponentPosition activeReferencePoint = RobotConstants.SCORING_POINT;
    
    /**
     * Reference point initial position in field coordinates
     * Default: field origin (0,0,0)
     */
    private static FieldPose referencePointInitialPosition = new FieldPose(0.0, 0.0, 0.0);

    // ========== DECODE 2025-2026 FIELD POSITIONS (BLUE ALLIANCE) ==========
    // All positions are defined for BLUE alliance (Y > 0, toward Blue Wall)
    // RED positions are auto-generated by mirroring across x-axis
    
    // Start positions
    public static final FieldPose START_NEAR = new FieldPose(-56, -56, 56);  // along alliance wall
    public static final FieldPose START_FAR = new FieldPose(72, -12, -90.0);
    
    // Artifact intake positions (3 rows of coral)
    public static final FieldPose INTAKE_1_START = new FieldPose(-12, -(37.0 - RobotConstants.ROBOT_LENGTH), -90.0);
    public static final FieldPose INTAKE_1_FINISH = INTAKE_1_START.offset(0, -20, 0);
    public static final FieldPose INTAKE_2_START = INTAKE_1_START.offset(24, 0, 0);
    public static final FieldPose INTAKE_2_FINISH = INTAKE_2_START.offset(0, -20, 0);
    public static final FieldPose INTAKE_3_START = INTAKE_2_START.offset(24, 0, 0);
    public static final FieldPose INTAKE_3_FINISH = INTAKE_3_START.offset(0, -20, 0);

    // Shooting positions (targeting Red GOAL)
    public static final FieldPose SHOOTING_CLOSE = new FieldPose(-31.5, -24, 58.7);
    public static final FieldPose SHOOTING_MID = new FieldPose(0.0, 36.0, 180.0);
    public static final FieldPose SHOOTING_LONG = new FieldPose(0.0, 24.0, 180.0);
    
    // Utility positions
    public static final FieldPose BASE_ZONE = new FieldPose(-60.0, 60.0, 315.0);
    public static final FieldPose LOADING_ZONE = new FieldPose(-60.0, 36.0, 180.0);
    public static final FieldPose SECRET_TUNNEL = new FieldPose(0.0, 72.0, 270.0);
    public static final FieldPose GATE_ZONE = new FieldPose(12.0, 72.0, 270.0);
    public static final FieldPose PARKING = new FieldPose(-48.0, 48.0, 315.0);
    
    // === APRILTAG & OBELISK POSITIONS ===
    
    // GOAL positions (for distance calculations and targeting)
    public static final FieldPose GOAL = new FieldPose(0.0, -72.0, -90);            // Blue Alliance GOAL
    
    // GOAL AprilTags (for shooting targeting)
    public static final FieldPose GOAL_APRILTAG = new FieldPose(0.0, -72.0, -90.0);   // Tag 20
    
    // OBELISK AprilTags (position varies - approximate center outside Blue wall)
    public static final FieldPose OBELISK_POSITION = new FieldPose(0.0, 72.0, 270.0);
    public static final FieldPose OBELISK_TAG_21 = new FieldPose(0.0, 72.0, 270.0);       // MOTIF face 1
    public static final FieldPose OBELISK_TAG_22 = new FieldPose(0.0, 72.0, 270.0);       // MOTIF face 2
    public static final FieldPose OBELISK_TAG_23 = new FieldPose(0.0, 72.0, 270.0);       // MOTIF face 3

    // ========== POSITION ACCESS METHODS ==========

    public static FieldPose getRedPosition(FieldPose bluePosition) {
        return bluePosition.mirror("x");
    }


    public static FieldPose getBluePosition(String positionName) {
        try {
            java.lang.reflect.Field field = FieldPositions.class.getField(positionName);
            if (field.getType() == FieldPose.class) {
                return (FieldPose) field.get(null);
            }
        } catch (Exception e) {
            // Position not found
        }
        return null;
    }
    

    public static FieldPose getRedPosition(String positionName) {
        return getBluePosition(positionName).mirror("x");

    }
    
    // ========== REFERENCE POINT MANAGEMENT ==========
    
    /**
     * Sets the active reference point that MotionExecutor will use
     * 
     * @param referencePoint The ComponentPosition to use as reference point
     */
    public static void setActiveReferencePoint(ComponentPosition referencePoint) {
        activeReferencePoint = referencePoint;
    }
    
    /**
     * Gets the current active reference point
     * 
     * @return Current active reference point
     */
    public static ComponentPosition getActiveReferencePoint() {
        return activeReferencePoint;
    }
    
    /**
     * Sets the reference point initial position in field coordinates
     * This method should be called with the MotionExecutor instance to update odometry
     * 
     * @param position Field position where the reference point should be initially positioned
     * @param motionExecutor MotionExecutor instance to update (calls resetToFieldOrigin)
     */
    public static void setReferencePointInitialPosition(FieldPose position, MotionExecutor motionExecutor) {
        referencePointInitialPosition = new FieldPose(position);
        
        // Update MotionExecutor odometry to this position
        Pose2D fieldOrigin = new Pose2D(
            DistanceUnit.INCH, position.x, position.y,
            AngleUnit.DEGREES, position.heading
        );
        motionExecutor.resetToFieldOrigin(fieldOrigin);
    }
    
    /**
     * Sets the reference point initial position to field origin (0,0,0)
     * 
     * @param motionExecutor MotionExecutor instance to update (calls resetToFieldOrigin)
     */
    public static void setReferencePointToFieldOrigin(MotionExecutor motionExecutor) {
        setReferencePointInitialPosition(new FieldPose(0.0, 0.0, 0.0), motionExecutor);
    }
    
    /**
     * Sets the reference point initial position to any predefined position
     * 
     * @param position Any FieldPose (can be BLUE or RED position)
     * @param motionExecutor MotionExecutor instance to update
     */
    public static void setReferencePointToPosition(FieldPose position, MotionExecutor motionExecutor) {
        setReferencePointInitialPosition(position, motionExecutor);
    }
    
    /**
     * Gets the current reference point initial position
     * 
     * @return Current reference point initial position in field coordinates
     */
    public static FieldPose getReferencePointInitialPosition() {
        return new FieldPose(referencePointInitialPosition);
    }
}
